"""MyTool: runtime state inspection and configuration for the agent loop."""

from __future__ import annotations

import time
import re
from pathlib import Path
from typing import TYPE_CHECKING, Any

from loguru import logger

from OriginAgent.agent.subagent import SubagentStatus
from OriginAgent.agent.tools.base import Tool

if TYPE_CHECKING:
    from OriginAgent.agent.loop import AgentLoop
    from OriginAgent.agent.introspection.service import RuntimeIntrospectionService


EVOLUTION_MANUAL_OVERRIDE_DISABLED = (
    "Evolution manual override is disabled. Set evolution.allow_manual_override=true in config to enable."
)


def _has_real_attr(obj: Any, key: str) -> bool:
    """Check if obj has a real (explicitly set) attribute, not auto-generated by mock."""
    if isinstance(obj, dict):
        return key in obj
    d = getattr(obj, "__dict__", None)
    if d is not None and key in d:
        return True
    for cls in type(obj).__mro__:
        if key in cls.__dict__:
            return True
    return False


class MyTool(Tool):
    """Check and set the agent loop's runtime configuration."""

    BLOCKED = frozenset({
        # Core infrastructure
        "bus", "provider", "_running", "tools",
        # Config management
        "_runtime_vars",
        # Subsystems
        "runner", "sessions", "consolidator",
        "dream", "auto_compact", "context", "commands",
        # Sensitive runtime state (credentials, message routing, task tracking)
        "_mcp_servers", "_mcp_stacks", "_pending_queues",
        "_session_locks", "_active_tasks", "_background_tasks",
        # Security boundaries (inspect + modify both blocked)
        "restrict_to_workspace", "channels_config",
        "_concurrency_gate", "_unified_session", "_extra_hooks",
    })

    READ_ONLY = frozenset({
        "subagents",  # observable but replacing it would break the system
        "_current_iteration",  # updated by runner only
        "exec_config",  # inspect allowed (e.g. check sandbox), modify blocked
        "web_config",  # inspect allowed (e.g. check enable), modify blocked
    })

    _DENIED_ATTRS = frozenset({
        "__class__", "__dict__", "__bases__", "__subclasses__", "__mro__",
        "__init__", "__new__", "__reduce__", "__getstate__", "__setstate__",
        "__del__", "__call__", "__getattr__", "__setattr__", "__delattr__",
        "__code__", "__globals__", "func_globals", "func_code",
        "__wrapped__", "__closure__",
    })

    # Sub-field names that are sensitive regardless of parent path
    _SENSITIVE_NAMES = frozenset({
        "apikey", "accesskey", "accesstoken", "refreshtoken", "privatekey",
        "authorization", "auth", "token", "password", "secret", "credential",
    })
    _SCRATCHPAD_KEY_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_-]{0,63}$")
    _SCRATCHPAD_RESERVED = frozenset({
        "scratchpad", "workspace", "web_config", "exec_config", "subagents",
    })
    EVOLUTION_CONTROL_ACTIONS = frozenset({
        "suppress_signal",
        "resume_signal",
        "run_maintenance",
        "force_cleanup",
        "run_feedback_calibration",
        "retry_trial",
        "rollback_artifact",
        "clear_config_overlay",
        "execute_evolution_action",
    })
    EVOLUTION_READ_ACTIONS = frozenset({
        "evolution_status",
        "list_evolution_actions",
        "list_evolution_signals",
        "list_evolution_proposals",
        "inspect_signal",
        "inspect_evolution_proposal",
        "explain_evolution_health",
        "list_evolution_recommendations",
        "preview_evolution_action",
        "generate_evolution_report",
        "validate_evolution_schema",
        "list_config_overlay",
    })

    @classmethod
    def _is_sensitive_field_name(cls, name: str) -> bool:
        normalized = re.sub(r"[_\-.]", "", name).lower()
        if normalized in cls._SENSITIVE_NAMES:
            return True
        if normalized.startswith("authorization"):
            return True
        parts = [
            part.lower()
            for part in re.split(r"[_\-.]|(?<=[a-z0-9])(?=[A-Z])", name)
            if part
        ]
        return any(part in {"auth", "token", "password", "secret", "credential"} for part in parts)

    RESTRICTED: dict[str, dict[str, Any]] = {
        "max_iterations":        {"type": int, "min": 1,   "max": 100},
        "context_window_tokens": {"type": int, "min": 4096, "max": 1_000_000},
        "model":                 {"type": str, "min_len": 1},
    }

    _MAX_RUNTIME_KEYS = 64

    def __init__(
        self,
        loop: AgentLoop,
        modify_allowed: bool = True,
        introspection_service: RuntimeIntrospectionService | None = None,
    ) -> None:
        self._loop = loop
        self._introspection_service = introspection_service
        self._modify_allowed = modify_allowed
        self._channel = ""
        self._chat_id = ""

    def __deepcopy__(self, memo: dict[int, Any]) -> MyTool:
        cls = self.__class__
        result = cls.__new__(cls)
        memo[id(self)] = result
        result._loop = self._loop
        result._introspection_service = self._introspection_service
        result._modify_allowed = self._modify_allowed
        result._channel = self._channel
        result._chat_id = self._chat_id
        return result

    def set_context(self, channel: str, chat_id: str) -> None:
        self._channel = channel
        self._chat_id = chat_id

    @property
    def name(self) -> str:
        return "my"

    @property
    def description(self) -> str:
        base = (
            "Check and set your own runtime state.\n"
            "Actions: check, set, suppress_signal, resume_signal, run_maintenance, "
            "force_cleanup, run_feedback_calibration, inspect_signal, "
            "inspect_evolution_proposal, explain_evolution_health, "
            "list_evolution_recommendations, preview_evolution_action, "
            "generate_evolution_report, retry_trial, rollback_artifact, "
            "evolution_status, list_evolution_actions, list_evolution_signals, "
            "list_evolution_proposals, validate_evolution_schema, list_config_overlay, "
            "clear_config_overlay.\n"
            "- check (no key): full config overview — start here.\n"
            "- check (key): drill into a value. Dot-paths allowed "
            "(e.g. '_last_usage.prompt_tokens', 'web_config.enable').\n"
            "- set (key, value): change only max_iterations, context_window_tokens, model, "
            "or store notes under a simple scratchpad key. "
            "Scratchpad keys persist across turns but not restarts.\n"
            "- evolution inspect/explain/list/preview/report actions are read-only operator views.\n"
            "- evolution control actions and retry_trial are writes and require "
            "learning.evolution.allow_manual_override=true.\n"
            "Key values: _current_iteration (current progress), "
            "max_iterations - _current_iteration = remaining iterations.\n"
            "Note: web_config and exec_config are readable but read-only.\n"
            "\n"
            "When to use:\n"
            "- User asks about your model, settings, or token usage → check that key.\n"
            "- A tool fails or behaves unexpectedly → check the related config to diagnose.\n"
            "- User asks you to remember a preference for this session → set to store it in your scratchpad.\n"
            "- About to start a large task → check context_window_tokens and max_iterations first."
        )
        if not self._modify_allowed:
            base += "\nREAD-ONLY MODE: set is disabled."
        else:
            base += (
                "\nIMPORTANT: Before setting state, predict the potential impact. "
                "If the operation could cause crashes or instability "
                "(e.g. changing model), warn the user first."
            )
        return base

    @property
    def parameters(self) -> dict[str, Any]:
        return {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string",
                    "enum": [
                        "check",
                        "set",
                        "suppress_signal",
                        "resume_signal",
                        "run_maintenance",
                        "force_cleanup",
                        "run_feedback_calibration",
                        "evolution_status",
                        "list_evolution_actions",
                        "list_evolution_signals",
                        "list_evolution_proposals",
                        "inspect_signal",
                        "inspect_evolution_proposal",
                        "explain_evolution_health",
                        "list_evolution_recommendations",
                        "preview_evolution_action",
                        "generate_evolution_report",
                        "validate_evolution_schema",
                        "list_config_overlay",
                        "retry_trial",
                        "rollback_artifact",
                        "clear_config_overlay",
                        "execute_evolution_action",
                    ],
                    "description": "Action to perform",
                },
                "key": {
                    "type": "string",
                    "description": "Key to check or set. Dot-paths are allowed for check only. "
                    "For set, use max_iterations/context_window_tokens/model or a simple scratchpad key. "
                    "For suppress_signal/resume_signal/inspect_signal, use the opportunity_id. "
                    "For inspect_evolution_proposal/retry_trial, use the proposal_id. "
                    "For preview_evolution_action, key can be the target id.",
                },
                "value": {
                    "description": "New value (for set), an optional reason string/object for evolution control actions, "
                    "or an object for preview_evolution_action/generate_evolution_report.",
                },
            },
            "required": ["action"],
            "additionalProperties": False,
        }

    def _audit(self, action: str, detail: str) -> None:
        session = f"{self._channel}:{self._chat_id}" if self._channel else "unknown"
        logger.info("self.{} | {} | session:{}", action, detail, session)

    # ------------------------------------------------------------------
    # Path resolution
    # ------------------------------------------------------------------

    def _loop_summary(self) -> dict[str, Any]:
        if self._introspection_service is not None:
            return self._introspection_service.current_loop_summary()
        return {
            "max_iterations": getattr(self._loop, "max_iterations", None),
            "context_window_tokens": getattr(self._loop, "context_window_tokens", None),
            "model": getattr(self._loop, "model", None),
            "workspace": getattr(self._loop, "workspace", None),
            "provider_retry_mode": getattr(self._loop, "provider_retry_mode", None),
            "max_tool_result_chars": getattr(self._loop, "max_tool_result_chars", None),
            "_current_iteration": getattr(self._loop, "_current_iteration", None),
            "web_config": getattr(self._loop, "web_config", None),
            "exec_config": getattr(self._loop, "exec_config", None),
            "subagents": getattr(self._loop, "subagents", None),
            "_last_usage": getattr(self._loop, "_last_usage", None),
            "scratchpad": getattr(self._loop, "_runtime_vars", {}),
        }

    def _resolve_path(self, path: str) -> tuple[Any, str | None]:
        parts = path.split(".")
        root = self._loop_summary()
        obj: Any = root
        used_summary = True
        for index, part in enumerate(parts):
            if part in self._DENIED_ATTRS or part.startswith("__"):
                return None, f"'{part}' is not accessible"
            if part in self.BLOCKED:
                return None, f"'{part}' is not accessible"
            if self._is_sensitive_field_name(part):
                return None, f"'{part}' is not accessible"
            try:
                if isinstance(obj, dict):
                    if part in obj:
                        obj = obj[part]
                    else:
                        if index == 0:
                            used_summary = False
                            obj = self._loop
                            if not _has_real_attr(obj, part):
                                return None, f"'{part}' not found"
                            obj = getattr(obj, part)
                            continue
                        return None, f"'{part}' not found in dict"
                else:
                    if not _has_real_attr(obj, part):
                        return None, f"'{part}' not found"
                    obj = getattr(obj, part)
            except (KeyError, AttributeError) as e:
                return None, f"'{part}' not found: {e}"
        if not used_summary and "." not in path and not _has_real_attr(self._loop, path):
            return None, f"'{path}' not found"
        return obj, None

    @staticmethod
    def _validate_key(key: str | None, label: str = "key") -> str | None:
        if not key or not key.strip():
            return f"Error: '{label}' cannot be empty or whitespace"
        return None

    # ------------------------------------------------------------------
    # Smart formatting
    # ------------------------------------------------------------------

    @staticmethod
    def _format_status(st: SubagentStatus, indent: str = "  ") -> str:
        elapsed = time.monotonic() - st.started_at
        tool_summary = ", ".join(
            f"{e.get('name', '?')}({e.get('status', '?')})" for e in st.tool_events[-5:]
        ) or "none"
        lines = [
            f"{indent}phase: {st.phase}, iteration: {st.iteration}, elapsed: {elapsed:.1f}s",
            f"{indent}tools: {tool_summary}",
            f"{indent}usage: {st.usage or 'n/a'}",
        ]
        if st.error:
            lines.append(f"{indent}error: {st.error}")
        if st.stop_reason:
            lines.append(f"{indent}stop_reason: {st.stop_reason}")
        return "\n".join(lines)

    @staticmethod
    def _format_value(val: Any, key: str = "") -> str:
        if isinstance(val, SubagentStatus):
            header = f"Subagent [{val.task_id}] '{val.label}'"
            detail = MyTool._format_status(val, "  ")
            return f"{header}\n  task: {val.task_description}\n{detail}"
        # SubagentManager: delegate to its _task_statuses dict
        if hasattr(val, "_task_statuses") and isinstance(val._task_statuses, dict):
            return MyTool._format_value(val._task_statuses, key)
        if isinstance(val, dict) and val and isinstance(next(iter(val.values())), SubagentStatus):
            prefix = f"{key}: " if key else ""
            lines = [f"{prefix}{len(val)} subagent(s):"]
            for tid, st in val.items():
                detail = MyTool._format_status(st, "    ")
                lines.append(f"  [{tid}] '{st.label}'\n{detail}")
            return "\n".join(lines)
        if hasattr(val, "tool_names"):
            return f"tools: {len(val.tool_names)} registered — {val.tool_names}"
        # Scalar types — repr is fine
        if isinstance(val, (str, int, float, bool, type(None))):
            r = repr(val)
            return f"{key}: {r}" if key else r
        # Dict — small: show content; large: show keys for dot-path navigation
        if isinstance(val, dict):
            ks = list(val.keys())
            if not ks:
                return f"{key}: {{}}" if key else "{}"
            if len(ks) <= 5:
                r = repr(val)
                if len(r) <= 200:
                    return f"{key}: {r}" if key else r
            preview = ", ".join(str(k) for k in ks[:15])
            suffix = ", ..." if len(ks) > 15 else ""
            return f"{key}: {{{preview}{suffix}}}" if key else f"{{{preview}{suffix}}}"
        # List/tuple — count for large, repr for small
        if isinstance(val, (list, tuple)):
            if len(val) > 20:
                return f"{key}: [{len(val)} items]" if key else f"[{len(val)} items]"
            r = repr(val)
            return f"{key}: {r}" if key else r
        # Complex object — small Pydantic models: show values; others: show field names for navigation
        cls_name = type(val).__name__
        model_fields = getattr(type(val), "model_fields", None)
        if model_fields:
            fields = list(model_fields.keys())
            if len(fields) <= 8:
                # Small config objects: show field=value pairs
                pairs = []
                for f in fields:
                    fv = getattr(val, f, "?")
                    if MyTool._is_sensitive_field_name(f):
                        continue
                    if isinstance(fv, (str, int, float, bool, type(None))):
                        pairs.append(f"{f}={fv!r}")
                    else:
                        pairs.append(f"{f}=<{type(fv).__name__}>")
                preview = ", ".join(pairs)
                return f"{key}: {preview}" if key else preview
        else:
            fields = [
                a for a in getattr(val, "__dict__", {})
                if not a.startswith("__") and not MyTool._is_sensitive_field_name(str(a))
            ]
        if fields:
            preview = ", ".join(str(f) for f in fields[:20])
            suffix = ", ..." if len(fields) > 20 else ""
            return f"{key}: <{cls_name}> [{preview}{suffix}]" if key else f"<{cls_name}> [{preview}{suffix}]"
        r = repr(val)
        return f"{key}: {r}" if key else r

    # ------------------------------------------------------------------
    # Action dispatch
    # ------------------------------------------------------------------

    async def execute(
        self,
        action: str,
        key: str | None = None,
        value: Any = None,
        **_kwargs: Any,
    ) -> str:
        if action in ("inspect", "check"):
            return self._inspect(key)
        if action in self.EVOLUTION_READ_ACTIONS:
            return self._evolution_read(action, key, value)
        if action in self.EVOLUTION_CONTROL_ACTIONS:
            return self._evolution_control(action, key, value)
        if not self._modify_allowed:
            return "Error: set is disabled (tools.my.allow_set is false)"
        if action in ("modify", "set"):
            return self._modify(key, value)
        return f"Unknown action: {action}"

    # -- evolution control plane --

    def _evolution_read(self, action: str, key: str | None, value: Any = None) -> str:
        plane = self._evolution_control_plane()

        if action == "evolution_status":
            result = plane.status()
            self._audit("evolution_read", "evolution_status")
            return f"Evolution control-plane status: {result!r}"
        if action == "list_evolution_actions":
            result = plane.list_actions()
            self._audit("evolution_read", "list_evolution_actions")
            return f"Evolution control-plane actions: {result!r}"
        if action == "list_evolution_signals":
            result = plane.list_signals(**self._signal_filters(value))
            self._audit("evolution_read", "list_evolution_signals")
            return f"Evolution signals: {result!r}"
        if action == "list_evolution_proposals":
            result = plane.list_proposals(**self._proposal_filters(value))
            self._audit("evolution_read", "list_evolution_proposals")
            return f"Evolution proposals: {result!r}"
        if action == "inspect_signal":
            if err := self._validate_key(key, "opportunity_id"):
                return err
            result = plane.inspect_signal(key or "")
            self._audit("evolution_read", f"inspect_signal {key}")
            return f"Evolution signal inspection: {result!r}"
        if action == "inspect_evolution_proposal":
            if err := self._validate_key(key, "proposal_id"):
                return err
            result = plane.inspect_proposal(key or "")
            self._audit("evolution_read", f"inspect_evolution_proposal {key}")
            return f"Evolution proposal inspection: {result!r}"
        if action == "explain_evolution_health":
            result = plane.explain_health()
            self._audit("evolution_read", "explain_evolution_health")
            return f"Evolution health explanation: {result!r}"
        if action == "list_evolution_recommendations":
            result = plane.list_recommendations()
            self._audit("evolution_read", "list_evolution_recommendations")
            return f"Evolution recommendations: {result!r}"
        if action == "preview_evolution_action":
            if not isinstance(value, dict):
                return "Error: preview_evolution_action value must be an object"
            action_kind = str(value.get("action_kind") or value.get("operation") or "").strip()
            if not action_kind:
                return "Error: preview_evolution_action requires value.action_kind"
            target_id = str(value.get("target_id") or key or "").strip()
            fixtures = value.get("fixtures")
            if fixtures is not None and not isinstance(fixtures, dict):
                return "Error: preview_evolution_action fixtures must be an object mapping relative paths to text"
            result = plane.preview_action(
                action_kind,
                target_id=target_id,
                reason=self._evolution_reason(value),
                fixtures={
                    str(path): str(content)
                    for path, content in (fixtures or {}).items()
                },
                force_cleanup=bool(value.get("force_cleanup", False)),
                artifact_type=str(value.get("artifact_type") or ""),
                artifact_name=str(value.get("artifact_name") or ""),
                snapshot_id=str(value.get("snapshot_id") or ""),
                period_days=self._coerce_period_days(value.get("period_days"), default=7),
            )
            self._audit("evolution_read", f"preview_evolution_action {action_kind} {target_id}")
            return f"Evolution action preview: {result!r}"
        if action == "generate_evolution_report":
            period_days = 7
            if isinstance(value, dict):
                period_days = self._coerce_period_days(value.get("period_days"), default=7)
            elif value is not None:
                period_days = self._coerce_period_days(value, default=7)
            elif key:
                period_days = self._coerce_period_days(key, default=7)
            report = plane.generate_report(period_days=period_days)
            self._audit("evolution_read", f"generate_evolution_report {period_days}d")
            return f"Evolution report:\n\n{report}"
        if action == "validate_evolution_schema":
            result = plane.execute_action("validate_schema")
            self._audit("evolution_read", "validate_evolution_schema")
            return f"Evolution schema validation: {result!r}"
        if action == "list_config_overlay":
            result = plane.execute_action("list_config_overlay")
            self._audit("evolution_read", "list_config_overlay")
            return f"Evolution config overlay: {result!r}"
        return f"Unknown action: {action}"

    def _evolution_control(self, action: str, key: str | None, value: Any) -> str:
        plane = self._evolution_control_plane()
        if action == "execute_evolution_action":
            if not isinstance(value, dict):
                return "Error: execute_evolution_action value must be an object"
            action_kind = str(value.get("action_kind") or value.get("operation") or "").strip()
            if not action_kind:
                return "Error: execute_evolution_action requires value.action_kind"
            result = plane.execute_action(
                action_kind,
                **self._control_plane_kwargs(key, value),
            )
            self._audit("evolution_control", f"execute_evolution_action {action_kind}")
            if not result.get("allowed", True) and result.get("message") == EVOLUTION_MANUAL_OVERRIDE_DISABLED:
                return EVOLUTION_MANUAL_OVERRIDE_DISABLED
            return f"Evolution control-plane action completed: {result!r}"

        if action == "retry_trial":
            if err := self._validate_key(key, "proposal_id"):
                return err
            fixtures = value.get("fixtures") if isinstance(value, dict) else None
            if fixtures is not None and not isinstance(fixtures, dict):
                return "Error: retry_trial fixtures must be an object mapping relative paths to text"
            result = plane.execute_action(
                action,
                target_id=key or "",
                fixtures={str(path): str(content) for path, content in (fixtures or {}).items()},
            )
            self._audit("evolution_control", f"retry_trial {key}")
            if not result.get("allowed", True) and result.get("message") == EVOLUTION_MANUAL_OVERRIDE_DISABLED:
                return EVOLUTION_MANUAL_OVERRIDE_DISABLED
            return f"Evolution trial retry completed: {result!r}"

        if action == "run_feedback_calibration":
            result = plane.execute_action(action)
            self._audit("evolution_control", "run_feedback_calibration")
            if not result.get("allowed", True) and result.get("message") == EVOLUTION_MANUAL_OVERRIDE_DISABLED:
                return EVOLUTION_MANUAL_OVERRIDE_DISABLED
            return f"Evolution feedback calibration completed: {result!r}"

        if action in {"run_maintenance", "force_cleanup"}:
            result = plane.execute_action(action, force_cleanup=(action == "force_cleanup"))
            self._audit("evolution_control", action)
            if not result.get("allowed", True) and result.get("message") == EVOLUTION_MANUAL_OVERRIDE_DISABLED:
                return EVOLUTION_MANUAL_OVERRIDE_DISABLED
            return f"Evolution maintenance completed: {result!r}"

        if action == "rollback_artifact":
            if not isinstance(value, dict):
                return "Error: rollback_artifact value must be an object with artifact_type and artifact_name"
            result = plane.execute_action(action, **self._control_plane_kwargs(key, value))
            self._audit("evolution_control", "rollback_artifact")
            if not result.get("allowed", True) and result.get("message") == EVOLUTION_MANUAL_OVERRIDE_DISABLED:
                return EVOLUTION_MANUAL_OVERRIDE_DISABLED
            return f"Evolution rollback completed: {result!r}"

        if action == "clear_config_overlay":
            result = plane.execute_action(action, reason=self._evolution_reason(value))
            self._audit("evolution_control", "clear_config_overlay")
            if not result.get("allowed", True) and result.get("message") == EVOLUTION_MANUAL_OVERRIDE_DISABLED:
                return EVOLUTION_MANUAL_OVERRIDE_DISABLED
            return f"Evolution config overlay cleared: {result!r}"

        if err := self._validate_key(key, "opportunity_id"):
            return err
        reason = self._evolution_reason(value)
        if action == "suppress_signal":
            result = plane.execute_action(action, target_id=key or "", reason=reason)
            self._audit("evolution_control", f"suppress_signal {key}")
            if not result.get("allowed", True) and result.get("message") == EVOLUTION_MANUAL_OVERRIDE_DISABLED:
                return EVOLUTION_MANUAL_OVERRIDE_DISABLED
            signal = result.get("result") if isinstance(result.get("result"), dict) else None
            if not signal:
                return f"Error: opportunity signal '{key}' not found or cannot be suppressed"
            return f"Suppressed opportunity signal {signal.get('opportunity_id')}: {signal.get('suppression_reason')}"
        if action == "resume_signal":
            result = plane.execute_action(action, target_id=key or "", reason=reason)
            self._audit("evolution_control", f"resume_signal {key}")
            if not result.get("allowed", True) and result.get("message") == EVOLUTION_MANUAL_OVERRIDE_DISABLED:
                return EVOLUTION_MANUAL_OVERRIDE_DISABLED
            signal = result.get("result") if isinstance(result.get("result"), dict) else None
            if not signal:
                return f"Error: opportunity signal '{key}' not found or is not suppressed"
            return f"Resumed opportunity signal {signal.get('opportunity_id')}"
        return f"Unknown action: {action}"

    def _evolution_control_plane(self) -> Any:
        from OriginAgent.agent.evolution_control_plane import EvolutionControlPlane

        return EvolutionControlPlane(self._workspace_path(), self._evolution_config())

    def _control_plane_kwargs(self, key: str | None, value: dict[str, Any]) -> dict[str, Any]:
        fixtures = value.get("fixtures")
        if fixtures is not None and not isinstance(fixtures, dict):
            fixtures = {}
        return {
            "target_id": str(value.get("target_id") or key or "").strip(),
            "reason": self._evolution_reason(value),
            "fixtures": {str(path): str(content) for path, content in (fixtures or {}).items()},
            "force_cleanup": bool(value.get("force_cleanup", False)),
            "artifact_type": str(value.get("artifact_type") or ""),
            "artifact_name": str(value.get("artifact_name") or ""),
            "snapshot_id": str(value.get("snapshot_id") or ""),
            "period_days": self._coerce_period_days(value.get("period_days"), default=7),
        }

    @staticmethod
    def _signal_filters(value: Any) -> dict[str, Any]:
        if not isinstance(value, dict):
            return {}
        filters: dict[str, Any] = {}
        if value.get("status") is not None:
            filters["status"] = str(value.get("status") or "")
        if value.get("kind") is not None:
            filters["kind"] = str(value.get("kind") or "")
        if value.get("limit") is not None:
            try:
                filters["limit"] = int(value.get("limit"))
            except (TypeError, ValueError):
                pass
        return filters

    @staticmethod
    def _proposal_filters(value: Any) -> dict[str, Any]:
        if not isinstance(value, dict):
            return {}
        filters: dict[str, Any] = {}
        if value.get("status") is not None:
            filters["status"] = str(value.get("status") or "")
        if value.get("proposal_type") is not None:
            filters["proposal_type"] = str(value.get("proposal_type") or "")
        if value.get("limit") is not None:
            try:
                filters["limit"] = int(value.get("limit"))
            except (TypeError, ValueError):
                pass
        return filters

    def _evolution_config(self) -> Any | None:
        if _has_real_attr(self._loop, "evolution_config"):
            return getattr(self._loop, "evolution_config", None)
        return None

    def _workspace_path(self) -> Path:
        workspace = getattr(self._loop, "workspace", None)
        return Path(workspace) if workspace is not None else Path(".")

    @staticmethod
    def _evolution_reason(value: Any) -> str:
        if isinstance(value, dict):
            value = value.get("reason", "")
        if value is None:
            return ""
        if isinstance(value, (str, int, float, bool)):
            return str(value)
        return ""

    @staticmethod
    def _coerce_period_days(value: Any, *, default: int) -> int:
        if isinstance(value, bool):
            return default
        try:
            return max(1, min(int(value), 90))
        except (TypeError, ValueError):
            return default

    # -- inspect --

    def _inspect(self, key: str | None) -> str:
        if not key:
            return self._inspect_all()
        top = key.split(".")[0]
        if top in self._DENIED_ATTRS or top.startswith("__"):
            return f"Error: '{top}' is not accessible"
        if key == "scratchpad":
            rv = {
                k: v for k, v in self._loop_summary().get("scratchpad", {}).items()
                if self._is_valid_scratchpad_key(k) is None
            }
            return self._format_value(rv, "scratchpad") if rv else "scratchpad is empty"
        obj, err = self._resolve_path(key)
        if err:
            # "scratchpad" alias for _runtime_vars
            # Fallback: check _runtime_vars for simple keys stored by modify
            scratchpad = self._loop_summary().get("scratchpad", {})
            if (
                "." not in key
                and key in scratchpad
                and self._is_valid_scratchpad_key(key) is None
            ):
                return self._format_value(scratchpad[key], key)
            return f"Error: {err}"
        # Guard against mock auto-generated attributes
        if "." not in key and key not in self._loop_summary() and not _has_real_attr(self._loop, key):
            scratchpad = self._loop_summary().get("scratchpad", {})
            if key in scratchpad and self._is_valid_scratchpad_key(key) is None:
                return self._format_value(scratchpad[key], key)
            return f"Error: '{key}' not found"
        return self._format_value(obj, key)

    def _inspect_all(self) -> str:
        summary = self._loop_summary()
        parts: list[str] = []
        # RESTRICTED keys
        for k in self.RESTRICTED:
            parts.append(self._format_value(summary.get(k), k))
        # Other useful top-level keys shown in description
        for k in ("workspace", "provider_retry_mode", "max_tool_result_chars", "_current_iteration", "web_config", "exec_config", "subagents"):
            if k in summary:
                parts.append(self._format_value(summary.get(k), k))
        # Token usage
        usage = summary.get("_last_usage")
        if usage:
            parts.append(self._format_value(usage, "_last_usage"))
        rv = summary.get("scratchpad", {})
        if rv:
            parts.append(self._format_value(rv, "scratchpad"))
        return "\n".join(parts)

    # -- modify --

    def _modify(self, key: str | None, value: Any) -> str:
        if err := self._validate_key(key):
            return err
        top = key.split(".")[0]
        if top in self.BLOCKED or top in self._DENIED_ATTRS or top.startswith("__") or self._is_sensitive_field_name(top):
            self._audit("modify", f"BLOCKED {key}")
            return f"Error: '{key}' is protected and cannot be modified"
        if top in self.READ_ONLY:
            self._audit("modify", f"READ_ONLY {key}")
            return f"Error: '{key}' is read-only and cannot be modified"
        if "." in key:
            self._audit("modify", f"BLOCKED dot-path set {key}")
            return "Error: dot-path set is not allowed; use a simple scratchpad key or a supported config key"
        if key in self.RESTRICTED:
            return self._modify_restricted(key, value)
        return self._modify_free(key, value)

    def _modify_restricted(self, key: str, value: Any) -> str:
        spec = self.RESTRICTED[key]
        expected = spec["type"]
        if expected is int and isinstance(value, bool):
            return f"Error: '{key}' must be {expected.__name__}, got bool"
        if not isinstance(value, expected):
            try:
                value = expected(value)
            except (ValueError, TypeError):
                return f"Error: '{key}' must be {expected.__name__}, got {type(value).__name__}"
        old = getattr(self._loop, key)
        if "min" in spec and value < spec["min"]:
            return f"Error: '{key}' must be >= {spec['min']}"
        if "max" in spec and value > spec["max"]:
            return f"Error: '{key}' must be <= {spec['max']}"
        if "min_len" in spec and len(str(value)) < spec["min_len"]:
            return f"Error: '{key}' must be at least {spec['min_len']} characters"
        setattr(self._loop, key, value)
        if key == "max_iterations" and hasattr(self._loop, "_sync_subagent_runtime_limits"):
            self._loop._sync_subagent_runtime_limits()
        self._audit("modify", f"{key}: {old!r} -> {value!r}")
        return f"Set {key} = {value!r} (was {old!r})"

    def _modify_free(self, key: str, value: Any) -> str:
        if _has_real_attr(self._loop, key):
            self._audit("modify", f"REJECTED runtime attr shadow {key}")
            return f"Error: scratchpad key '{key}' is reserved"
        if err := self._is_valid_scratchpad_key(key):
            self._audit("modify", f"REJECTED scratchpad key {key}: {err}")
            return f"Error: {err}"
        if callable(value):
            self._audit("modify", f"REJECTED callable {key}")
            return "Error: cannot store callable values"
        err = self._validate_json_safe(value)
        if err:
            self._audit("modify", f"REJECTED {key}: {err}")
            return f"Error: {err}"
        if key not in self._loop._runtime_vars and len(self._loop._runtime_vars) >= self._MAX_RUNTIME_KEYS:
            self._audit("modify", f"REJECTED {key}: max keys ({self._MAX_RUNTIME_KEYS}) reached")
            return f"Error: scratchpad is full (max {self._MAX_RUNTIME_KEYS} keys). Remove unused keys first."
        old = self._loop._runtime_vars.get(key)
        self._loop._runtime_vars[key] = value
        self._audit("modify", f"scratchpad.{key}: {old!r} -> {value!r}")
        return f"Set scratchpad.{key} = {value!r}"

    @classmethod
    def _is_valid_scratchpad_key(cls, key: str) -> str | None:
        if not cls._SCRATCHPAD_KEY_RE.fullmatch(key):
            return (
                "scratchpad key must match ^[A-Za-z][A-Za-z0-9_-]{0,63}$ "
                "and must not contain dots"
            )
        if (
            key in cls.BLOCKED
            or key in cls.READ_ONLY
            or key in cls.RESTRICTED
            or key in cls._SCRATCHPAD_RESERVED
            or cls._is_sensitive_field_name(key)
        ):
            return f"scratchpad key '{key}' is reserved"
        return None

    @classmethod
    def _validate_json_safe(cls, value: Any, depth: int = 0) -> str | None:
        if depth > 10:
            return "value nesting too deep (max 10 levels)"
        if isinstance(value, (str, int, float, bool, type(None))):
            return None
        if isinstance(value, list):
            for i, item in enumerate(value):
                if err := cls._validate_json_safe(item, depth + 1):
                    return f"list[{i}] contains {err}"
            return None
        if isinstance(value, dict):
            for k, v in value.items():
                if not isinstance(k, str):
                    return f"dict key must be str, got {type(k).__name__}"
                if err := cls._validate_json_safe(v, depth + 1):
                    return f"dict key '{k}' contains {err}"
            return None
        return f"unsupported type {type(value).__name__}"
