package main

import (
	"bbs-go/internal/permissions"
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"unicode"
)

func main() {
	if err := run(); err != nil {
		panic(err)
	}
}

func run() error {
	if err := validateDefinitions(); err != nil {
		return err
	}

	output, err := buildTypeScript()
	if err != nil {
		return err
	}

	path, err := outputPath()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	return os.WriteFile(path, output, 0644)
}

func validateDefinitions() error {
	seenCodes := make(map[string]struct{})
	seenKeys := make(map[string]string)
	for _, permission := range permissions.Permissions {
		if !permission.IsValid() {
			return fmt.Errorf("invalid permission definition: %#v", permission)
		}
		if _, ok := seenCodes[permission.Code]; ok {
			return fmt.Errorf("duplicate permission code: %s", permission.Code)
		}
		seenCodes[permission.Code] = struct{}{}

		key := permissionKey(permission.Code)
		if existing, ok := seenKeys[key]; ok {
			return fmt.Errorf("duplicate generated key %s for %s and %s", key, existing, permission.Code)
		}
		seenKeys[key] = permission.Code
	}
	return nil
}

func buildTypeScript() ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by `cd server && go run ./cmd/generator/permissions`; DO NOT EDIT.\n\n")
	buf.WriteString("export const PERMISSIONS = {\n")
	for _, permission := range permissions.Permissions {
		buf.WriteString(fmt.Sprintf("  %s: %q,\n", permissionKey(permission.Code), permission.Code))
	}
	buf.WriteString("} as const\n\n")
	buf.WriteString("export type PermissionCode =\n")
	buf.WriteString("  (typeof PERMISSIONS)[keyof typeof PERMISSIONS]\n\n")
	buf.WriteString("export const PERMISSION_LIST = [\n")
	for _, permission := range permissions.Permissions {
		buf.WriteString(fmt.Sprintf("  PERMISSIONS.%s,\n", permissionKey(permission.Code)))
	}
	buf.WriteString("] as const\n")
	return buf.Bytes(), nil
}

func permissionKey(code string) string {
	var words []string
	var current []rune
	var prevOriginal rune
	flush := func() {
		if len(current) == 0 {
			prevOriginal = 0
			return
		}
		words = append(words, string(current))
		current = nil
		prevOriginal = 0
	}

	for _, r := range code {
		if r == '.' || r == '-' || r == '_' {
			flush()
			continue
		}
		if unicode.IsUpper(r) && len(current) > 0 {
			if unicode.IsLower(prevOriginal) || unicode.IsDigit(prevOriginal) {
				flush()
			}
		}
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			current = append(current, unicode.ToUpper(r))
			prevOriginal = r
		}
	}
	flush()
	return strings.Join(words, "_")
}

func outputPath() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	candidates := []string{
		filepath.Join(wd, "..", "web", "lib", "auth", "permissions.generated.ts"),
		filepath.Join(wd, "web", "lib", "auth", "permissions.generated.ts"),
	}
	for _, candidate := range candidates {
		if _, err := os.Stat(filepath.Dir(candidate)); err == nil {
			return filepath.Clean(candidate), nil
		}
	}
	return filepath.Clean(candidates[0]), nil
}
