"""Smart-home fact store configuration."""

from OriginAgent.agent.facts import FactStoreConfig


SMART_HOME_FACT_STORE_CONFIG = FactStoreConfig(
    category_order=(
        "preference",
        "routine",
        "device",
        "policy",
        "safety",
        "temporary",
        "note",
    ),
    legacy_categories=("household",),
    valid_owners=("user", "assistant", "system", "unknown", "household"),
    high_risk_categories=("policy", "safety"),
    conflict_categories=("preference", "routine", "policy", "safety", "temporary"),
    high_risk_keywords=(
        "door lock",
        "unlock",
        "lock",
        "front door",
        "security",
        "alarm",
        "camera",
        "gas",
        "stove",
        "child",
        "baby",
        "elderly",
        "medication",
        "payment",
        "password",
        "key",
        "permission",
        "门锁",
        "开门",
        "解锁",
        "安防",
        "报警",
        "摄像头",
        "燃气",
        "煤气",
        "灶",
        "儿童",
        "孩子",
        "婴儿",
        "老人",
        "药",
        "支付",
        "密码",
        "权限",
    ),
    temporary_language=(
        "today",
        "tomorrow",
        "this week",
        "temporary",
        "for now",
        "just this time",
        "今天",
        "明天",
        "这周",
        "本周",
        "临时",
        "暂时",
        "先",
        "这次",
    ),
    uncertain_language=(
        "maybe",
        "usually",
        "sometimes",
        "probably",
        "around",
        "roughly",
        "可能",
        "一般",
        "有时",
        "大概",
        "差不多",
        "左右",
        "偶尔",
    ),
)
